### ISSUE TITLE
Error occurred while running or packaging:

### ISSUE THREAD

**Issue by masmsec** [flick-network/pkg-x86#1]
Initially, I has issued with installing pkg-x86. Even after installing node14.20.0 LTS and running the pkg-x86 on my windows 10 and 7 32bit arch, I got the below error, 

C:\Intel\node\pkg-x86>npm install -g pkg-x86
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated npmlog@4.1.2: This package is no longer supported.
npm WARN deprecated gauge@2.7.4: This package is no longer supported.
npm WARN deprecated are-we-there-yet@1.1.7: This package is no longer supported.

> node@14.21.3 preinstall C:\Users\XAN\AppData\Roaming\npm\node_modules\pkg-x86\node_modules\node
> node installArchSpecificPackage

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for node-win-x86@14.21.3: wanted {"os":"win32","arch":"x86"} (current: {"os":"win32","arch":"ia32"})
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  x86
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: ia32

I decided to use :
npm install -g pkg-x86 --force 

and everything seems to install well but what kept me on a spot is when it cant find the bundled pkg " Path to the bundled pkg binary"
node_modules/pkg/bin/pkg.js

is there anyway or command i need to run, so that I can be able to get the pkg.js file inside /pkg/bin folder ?

So my final result is 
C:\Intel\node\pkg-x86>node pkg-x86 -i index.js -o output.exe
Checking for the Node versions available in your system.
Using system Node.js version.
Starting the app check with Node.js 14...
No errors found. Starting the packaging process with pkg...
The system cannot find the path specified.
Error occurred while running or packaging: Command failed: C:\Intel\node\pkg-x86\node_modules\pkg\bin\pkg.js index.js -t node14-win-x86 -o output.exe

Please let me know how i can go about fixing this . or if there is a step-guide to accomplish compiling applications for 32bit,

**Comment by sivadasrajan** [comment]
What is the processor model in the computer that runs this code?

**Comment by masmsec** [comment]
I am currently running windows 10 32bit on a VMware with the processor Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz   2.30 GHz  (2 processors)

**Comment by masmsec** [comment]
I am currently running windows 10 32bit on a VMware with the processor Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz 2.30 GHz (2 processors)

I want to be able to be able to package nodejs applications for 32bit, Since I am trying to target legacy systems.

I will really appreciate it, if you can guide me on steps to take so that I can achieve this . the pkg.js is missing from node_modules/bin folder .

thank you

Sent with [Proton Mail](https://proton.me/mail/home) secure email.
